version: 2

models:
  - name: fct_cargo_logistics
    description: "The primary fact table for global cargo flight analytics, filtered to the latest batch."
    columns:
      - name: icao_24
        description: "Unique ICAO 24-bit address of the aircraft transponder."
        tests:
          - not_null

      - name: last_contact
        description: "Unix timestamp (seconds) for the last update received from the aircraft."
        tests:
          - not_null

      - name: is_latest_sync
        description: "Boolean flag identifying the most recent micro-batch."
        tests:
          - not_null